#162949040 Users should be able to create and view articles
andela/ah-robotics-frontend pull request #16
Opened 2019-02-20 18:43 UTC by jomasim

2019-02-22 10:45 UTC, Paulvitalis200 reviewed
Hey @jomasim,
This is good. It is working as expected. I was able to create an article and see it when I view all articles.

2019-02-22 11:38 UTC, waracci commented
You should work on redirecting a user to the article page after the article is created.

2019-02-22 11:41 UTC, sharkdevs commented
It is working, though there is a lot of loading and refresh. Maybe because of Heroku. Otherwise, very satisfactory

2019-02-22 12:55 UTC, Collins33 requested changes

2019-02-22 12:55 UTC, Collins33 commented on src/components/Article/index.js
> +  const fetchedArticle = article.article;
Use destructuring here

2019-02-22 12:55 UTC, Collins33 commented on src/components/Article/index.js
> +          src={(fetchedArticle && fetchedArticle.author.image)
can we have a variable to store values like `fetchedArticle.author.image`?

2019-02-22 12:55 UTC, Collins33 commented on src/components/Article/index.js
> +          style={{ marginTop: '2em' }}
Why is the styling here and not in a css file?

2019-02-22 12:55 UTC, Collins33 commented on src/components/ArticleEditor/article.editor.scss
> +.cke_contents .cke_bottom {
what is `cke`?

2019-02-22 12:55 UTC, Collins33 commented on src/components/ArticleEditor/index.jsx
> +              style={{ color: 'red' }}
Why are this styles here?

2019-02-22 12:55 UTC, Collins33 commented on src/components/ArticlesListing/ArticleItem.jsx
> +    <Item.Image src={(article.image) ? article.image : 'https://source.unsplash.com/random'} />
Is this link for the image a placeholder?

2019-02-22 12:55 UTC, Collins33 commented on src/components/ArticlesListing/index.js
> +  const allArticles = articles.articles;
Use destructuring here

2019-02-22 12:55 UTC, Collins33 commented on src/redux/actions/ArticleActions/articles.action.types.js
> +export const ARTICLE_FETCH = 'ARTICLE_FETCH';
Why did you name the file as articles.action.types.js?

2019-02-22 12:55 UTC, Collins33 commented on src/redux/actions/ArticleActions/articles.actions.test.js
> +  expect(articleFetch({}).type).toBe(types.ARTICLE_FETCH);
I expect you to test more than just the action type

2019-02-22 12:55 UTC, Collins33 commented on src/redux/reducers/ArticlesReducer/fetch.articles.reducer.js
> + ...state, ...action.payload, isFetching: false,
Should this appear like this?

2019-02-22 12:55 UTC, Collins33 commented on src/redux/sagas/ArticleSaga/postArticleSaga.js
> +      payload: { errors: error.response ? error.response.data.article.errors : { message: 'something went wrong' } },
What exact error message should we use here?

2019-02-23 09:18 UTC, jomasim commented on src/redux/reducers/ArticlesReducer/fetch.articles.reducer.js
> + ...state, ...action.payload, isFetching: false,
I have refactored the code

2019-02-23 09:29 UTC, jomasim commented
@Collins33 I have managed to resolve all the issues.

2019-02-23 18:41 UTC, Collins33 commented
When I test the application, I have to reload the page and this logs me out.

2019-02-23 19:36 UTC, Collins33 commented
When I add an article, it should redirect me to another page on the application

2019-02-23 20:35 UTC, jomasim commented
> When I add an article, it should redirect me to another page on the application

I can now redirect to the article page.

2019-02-23 20:37 UTC, jomasim commented
> When I test the application, I have to reload the page and this logs me out.

I have fixed the issue. The app now logs out only after someone clicks log out on the navbar.

2019-02-24 06:27 UTC, Teatoller commented
Hello @jomasim ,
I have tested the article feature and have been able to post an article.
The challenge @sharkdevs mentioned about slow loading images is an area of improvement.
I also ran the test and would advise

Regards
Steven Ennis

<img width="1267" alt="screenshot 2019-02-24 at 09 22 44" src="https://user-images.githubusercontent.com/39020475/53295901-42a42380-3816-11e9-9e03-91ee70dafea2.png">
 you correct for a failing snapshot test.

2019-02-24 09:01 UTC, Collins33 requested changes
When I post a long article, all of it appears on the home page. This makes the home page look weird.

2019-02-24 09:01 UTC, Collins33 commented on src/views/CreateArticleView/index.jsx
> +    if (isPosted) {
Why is there a timeout here?

2019-02-24 09:18 UTC, Teatoller reviewed
Hello @jomasim 
I did make a review asking that you refined a snapshot test that is failing.
Kindly look at the comment section.

Regards
Steven Ennis

2019-02-24 11:24 UTC, jomasim commented on src/views/CreateArticleView/index.jsx
> +    if (isPosted) {
I have managed to add a timeout as well as added a function to truncate the text on the homepage for long paragraphs.

2019-02-24 11:25 UTC, jomasim commented
> Hello @jomasim
> I did make a review asking that you refined a snapshot test that is failing.
> Kindly look at the comment section.
> 
> Regards
> Steven Ennis

@Teatoller I have fixed the failing test

2019-02-25 18:06 UTC, johnwayodi reviewed
@jomasim this is great work. I have tested and all the functionality works as expected.

2019-02-26 10:47 UTC, Collins33 approved these changes

2019-02-26 10:48 UTC, merged