#162949030 Setup environment for writing tests
andela/ah-robotics-frontend pull request #3
Opened 2019-02-07 08:08 UTC by jomasim

#### What does this PR do?
This PR sets up environment for writing tests.
#### Description of Task to be completed?
- [x] installed enzyme package
- [x] created setupTest.js file
- [x] updated app.test to use enzyme shallow instead of react-dom

#### How should this be manually tested?

1. Clone this repository on your local machine using 
```
 git clone https://github.com/andela/ah-robotics-frontend.git 
```
2. Change your working directory to the project's directory using 
```
cd ah-robotics-frontend
```
3. Change to the specific branch `ch-setting-testing-environment-162949030` using 
```
git checkout  ch-setting-testing-environment-162949030
```

4. Run `npm install` to install all the modules listed in the `package.json` file.

5. Run `npm test` command to run the tests.

<img width="704" alt="screenshot 2019-02-07 at 11 02 58" src="https://user-images.githubusercontent.com/9401930/52397840-f93e9f00-2ac7-11e9-9ba5-5a1d79add15a.png">

[#162949030](https://www.pivotaltracker.com/n/projects/2235171/stories/162949030)

2019-02-07 08:32 UTC, sharkdevs reviewed
There is a screen that comes up on running `npm test` which gives options to run the tests. Consider adding that description on the PR lest it takes a user by surprise. 
<img width="450" alt="screen shot 2019-02-07 at 11 30 12" src="https://user-images.githubusercontent.com/14871749/52399012-02ca0600-2acc-11e9-88c9-1c2d0f0783e4.png">

2019-02-07 09:04 UTC, jomasim commented
> There is a screen that comes up on running `npm test` which gives options to run the tests. Consider adding that description on the PR lest it takes a user by surprise.
> <img alt="screen shot 2019-02-07 at 11 30 12" width="450" src="https://user-images.githubusercontent.com/14871749/52399012-02ca0600-2acc-11e9-88c9-1c2d0f0783e4.png">

I have added --watchAll flag to enable you run all tests by default

2019-02-07 09:25 UTC, Teatoller commented
Hello @jomasim 
I have been able to test this feature branch and it is working as anticipated.
Regards
Steven Ennis

2019-02-07 09:59 UTC, waracci reviewed
Works as stipulated in your PR message!

<img width="561" alt="screenshot 2019-02-07 at 12 57 56" src="https://user-images.githubusercontent.com/6994982/52403638-39a61900-2ad8-11e9-8f53-deecb43ed9da.png">


Consider adding a blank line at the end of `setupTests.js` Github is complaining about it.

2019-02-07 11:34 UTC, Paulvitalis200 reviewed
Hey @jomasim,
I have been able to test this feature locally on my machine and it works as expected.

2019-02-10 05:39 UTC, Collins33 requested changes

2019-02-10 05:39 UTC, Collins33 commented on src/App.test.js
> +  it('app should render without crashing ', () => {
Remove the space after the crashing word

2019-02-10 09:08 UTC, jomasim commented on src/App.test.js
> +  it('app should render without crashing', () => {
@Collins33 I have removed the space.It looks fine now

2019-02-10 09:32 UTC, Teatoller requested changes
Hello Joma,

I have tested your feature branch and the noticeable difference is not that there is no test present.
You may need to revise the screenshot you have to the following.

<img width="764" alt="screenshot 2019-02-10 at 12 24 19" src="https://user-images.githubusercontent.com/39020475/52532054-d0204780-2d2f-11e9-982a-1634a647bc69.png">


Regards
Steven Ennis

2019-02-10 10:03 UTC, jomasim commented
> Hello Joma,
> 
> I have tested your feature branch and the noticeable difference is not that there is no test present.
> You may need to revise the screenshot you have to the following.
> 
> <img alt="screenshot 2019-02-10 at 12 24 19" width="764" src="https://user-images.githubusercontent.com/39020475/52532054-d0204780-2d2f-11e9-982a-1634a647bc69.png">
> 
> Regards
> Steven Ennis

@Teatoller The test runner checks for any changes in the tests before it runs. We don't have any change right now so you need to press a to run the all the tests. Let me update the instructions to make it easy for you.

2019-02-10 17:36 UTC, Teatoller approved these changes

2019-02-11 07:37 UTC, johnwayodi reviewed
Nice work, I was able to test it locally and got the same output.

2019-02-11 07:47 UTC, Collins33 approved these changes

2019-02-11 07:47 UTC, merged